#!/usr/bin/env python3
import sys
from pathlib import Path

app = Path(sys.argv[1])
vm_path = app / "app/src/main/java/dev/busung/s25uroot/InstallViewModel.kt"
vm = vm_path.read_text()

# temp_su.sock is root-owned by the bootstrap daemon. A shell/Shizuku cleanup
# must not fail just because a previous root daemon or a panic left that inode
# behind. The root helper already unlinks/rebinds this socket when UMH starts.
socket_entry = '            "/data/local/tmp/temp_su.sock",\n'
if socket_entry not in vm:
    raise SystemExit("temp_su.sock was not present in RMG_TEMP_PATHS")
vm = vm.replace(socket_entry, "", 1)

# Make the lifecycle explicit in the live log. We intentionally do not delete
# this path as shell: the root helper owns it and replaces it at bootstrap.
old_tail = '''        appendLog("[+] Workspace temporário limpo")
        appendLog("[+] Payload, helper e KernelSU serão regravados nesta sessão")
    }

    private suspend fun executeExploit(payload: File) {'''
new_tail = '''        appendLog("[+] Workspace temporário limpo")
        appendLog("[+] Payload, helper e KernelSU serão regravados nesta sessão")
        if (File(ROOT_BOOTSTRAP_SOCKET_PATH).exists()) {
            appendLog("[*] Socket bootstrap antigo detectado; o helper root vai substituí-lo durante o bootstrap")
        }
    }

    private suspend fun cleanupBootstrapSocketAfterInstall() {
        appendLog("[*] Removendo socket bootstrap usado nesta sessão")
        val cleanup = runHelper(
            "-c",
            "/system/bin/rm -f -- $ROOT_BOOTSTRAP_SOCKET_PATH",
        )
        if (cleanup.code != 0) {
            appendLog(
                "[!] KernelSU já está ativo, mas o socket bootstrap não pôde ser removido: " +
                    cleanup.output.ifBlank { "exit=${cleanup.code}" },
            )
            return
        }
        delay(50.milliseconds)
        if (File(ROOT_BOOTSTRAP_SOCKET_PATH).exists()) {
            appendLog("[!] KernelSU já está ativo, mas o socket bootstrap ainda está visível")
        } else {
            appendLog("[+] Socket bootstrap removido")
        }
    }

    private suspend fun executeExploit(payload: File) {'''
if old_tail not in vm:
    raise SystemExit("prepareFreshRuntimeWorkspace tail not found")
vm = vm.replace(old_tail, new_tail, 1)

# Once late-load + control verification succeeds, use the already-open root
# bootstrap channel to unlink its pathname. The daemon may keep its open fd,
# but no filesystem residue remains for the next payload implementation.
install_old = '''                setPhase(InstallPhase.LoadingKernelSu, app.getString(R.string.status_ksu_loading))
                installKernelSu(payloads)

                setPhase(InstallPhase.Installed, app.getString(R.string.status_ksu_active))'''
install_new = '''                setPhase(InstallPhase.LoadingKernelSu, app.getString(R.string.status_ksu_loading))
                installKernelSu(payloads)
                cleanupBootstrapSocketAfterInstall()

                setPhase(InstallPhase.Installed, app.getString(R.string.status_ksu_active))'''
if install_old not in vm:
    raise SystemExit("installKernelSu call site not found")
vm = vm.replace(install_old, install_new, 1)

const_anchor = '        private const val SHIZUKU_KSUD_STAGE_PATH = "/data/local/tmp/.ksud-stage"\n'
const_new = (
    const_anchor
    + '        private const val ROOT_BOOTSTRAP_SOCKET_PATH = "/data/local/tmp/temp_su.sock"\n'
)
if const_anchor not in vm:
    raise SystemExit("constant insertion point not found")
vm = vm.replace(const_anchor, const_new, 1)
vm_path.write_text(vm)

# Distinct v3 lab identity so it can coexist with the v2 APK even though each
# GitHub Actions runner signs debug APKs independently.
gradle_path = app / "app/build.gradle.kts"
gradle = gradle_path.read_text()
gradle = gradle.replace(
    'applicationId = "dev.busung.s25uroot.s908bofflinev2"',
    'applicationId = "dev.busung.s25uroot.s908bofflinev3"',
    1,
)
gradle = gradle.replace(
    'versionName = "0.2.65-s908b-offline-clean-v2"',
    'versionName = "0.2.65-s908b-offline-clean-v3"',
    1,
)
gradle_path.write_text(gradle)

for strings in (app / "app/src/main/res").glob("values*/strings.xml"):
    text = strings.read_text()
    text = text.replace(
        "Root My Galaxy — S908B Offline Lab v2",
        "Root My Galaxy — S908B Offline Lab v3",
    )
    strings.write_text(text)

# Profile text is generated by the v2 base patch; bump it for a clean record.
repo_path = app / "app/src/main/java/dev/busung/s25uroot/PayloadRepository.kt"
repo = repo_path.read_text()
repo = repo.replace(
    "b0s-S908BXXSMGZB2-offline-clean-v2",
    "b0s-S908BXXSMGZB2-offline-clean-v3",
)
repo = repo.replace(
    "GZB2 Offline Clean v2",
    "GZB2 Offline Clean v3",
)
repo_path.write_text(repo)

print("bootstrap_socket=helper-owned")
print("preclean_socket=nonfatal")
print("postinstall_socket_cleanup=enabled")
print("lab_variant=v3")
